version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladatabase:mysql
    ports:
      - 8080:80
    volumes:
      - "../:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladatabase
      JOOMLA_DB_PASSWORD: toor

  joomladatabase:
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: toor